default:  &default
    adapter: sqlite3
    database: db/db_python_shmup
    encoding: utf8
    pool: 5
    timeout: 5000

development:
    <<: *default
    database: db/db_python_shmup

test:
    <<: *default
    database: db/db_python_shmup_test
